services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    env_file:
      - ./user-service/.env
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - db
      - rabbitmq

  product-service:
    build: ./product-service
    ports:
      - "3001:3000"
    env_file:
      - ./product-service/.env
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - db
      - rabbitmq

  order-service:
    build: ./order-service
    ports:
      - "3002:3000"
    env_file:
      - ./order-service/.env
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - db
      - rabbitmq

  cart-service:
    build: ./cart-service
    ports:
      - "3003:3000"
    env_file:
      - ./cart-service/.env
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    volumes:
      - user-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  user-data:
